"""empty message

Revision ID: 332511b50fa1
Revises: 0b110fc9b3c6
Create Date: 2020-08-23 17:28:00.342667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332511b50fa1'
down_revision = '0b110fc9b3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking', sa.Boolean(), nullable=True))
    op.drop_column('artists', 'seek')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seek', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'seeking')
    # ### end Alembic commands ###
